### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by jroes** [infinitered/ProMotion-form#2]
I realize this is already marked as Coming Soon in the README.

I've given it a shot with a spec, and here's what I'm seeing:

```
  Simulate ./build/iPhoneSimulator-8.0-Development/ProMotion-form_spec.app
2014-09-20 12:13:50.609 ProMotion-form[32342:2302365] -[String _isResizable]: unrecognized selector sent to instance 0xce50e60
2014-09-20 12:13:50.614 ProMotion-form[32342:2302365] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-$
String _isResizable]: unrecognized selector sent to instance 0xce50e60'
*** First throw call stack:
(
        0   CoreFoundation                      0x02ab3df6 __exceptionPreprocess + 182
        1   libobjc.A.dylib                     0x005a8a97 objc_exception_throw + 44
        2   CoreFoundation                      0x02abba75 -[NSObject(NSObject) doesNotRecognizeSelector:] + 277
        3   CoreFoundation                      0x02a049c7 ___forwarding___ + 1047
        4   CoreFoundation                      0x02a0458e _CF_forwarding_prep_0 + 14
        5   UIKit                               0x0110becc -[UIImageView(Pretiling) _updatePretiledImageCacheForImage:] + 58
        6   UIKit                               0x00c1ef14 -[UIImageView _updateImageViewForOldImage:newImage:] + 299
        7   UIKit                               0x00c1b7b9 -[UIImageView setImage:] + 343
        8   ProMotion-form                      0x000143cb -[FXFormImagePickerCell update] + 239
        9   ProMotion-form                      0x0000d30b -[FXFormBaseCell setField:] + 66
        10  ProMotion-form                      0x0000b2d3 -[FXFormController tableView:willDisplayCell:forRowAtIndexPath:] + 250
```

I have a branch here - https://github.com/jroes/ProMotion-form/compare/image

The error confuses me to no end, and I'm not sure how to go about debugging it to be honest. Why is `UIImageView` sending a `String` selector to a `UIImage`?

**Comment by jamonholmgren** [comment]
@chrise86 Just saw this comment. Did you figure out your issue here?

**Comment by elzggr** [comment]
@jamonholmgren would you know if this issue was ever fixed?
I follow many of our posts and you always seem to lead me to someone or somewhere that has an answer haha

**Comment by jamonholmgren** [comment]
@elzggr Ha! Not always, I'm sure. Like on this one...

I haven't tested this lately, so I don't know the status. We might be able to just upgrade the underlying CocoaPod and have it work, but I'm not sure.

**Comment by chrise86** [comment]
@jamonholmgren I haven't had a chance to revisit this yet, but will have to very soon so will let you know.

**Comment by jamonholmgren** [comment]
:+1:

**Comment by goodwill** [comment]
Any updates? Just hit this same bug.

**Comment by tylerhoran** [comment]
Same Here. Any updates on the image field?

**Comment by jamonholmgren** [comment]
Unfortunately, no. Would you want to tackle this, to help us out? Most of the team is very busy with RedPotion/BluePotion right now.

**Comment by tylerhoran** [comment]
Sure. I'll give it a shot. But ruby motion is new for me and pretty unfamiliar.

**Comment by jamonholmgren** [comment]
Feel free to jump into [motioneers.herokuapp.com](http://motioneers.herokuapp.com) for help. :)

**Comment by tylerhoran** [comment]
@jamonholmgren setting the value to UIImage.new seems to do the trick. 

https://gist.github.com/tylerhoran/a7c0f04dbbdc7e5440a6

**Comment by jamonholmgren** [comment]
ProMotion-form has been officially deprecated. Thanks everyone!

http://jamonholmgren.com/deprecating-promotion-form/
