### ISSUE TITLE
Multi-select options without bitfield?

### ISSUE THREAD

**Issue by DiogoAndre** [infinitered/ProMotion-form#20]
I tried to figure it out myself, but just kept hitting a wall.  How can we have e field to be a multi-selectable options list without setting the type as `:bitfield`

It is possible with FXForms:

```objc
            
             // RegistrationForm.h
             @property (nonatomic, copy) NSArray *interests;

             // RegistrationForm.m
             //this is a multi-select options field - FXForms knows this because the
             //class of the field property is a collection (in this case, NSArray)
             
             @{FXFormFieldKey: @"interests",
               FXFormFieldDefaultValue: @[@"Videogames"],
               FXFormFieldOptions: @[@"Videogames", @"Animals", @"Cooking"]},
```

Maybe not possible at all because of how the form_data is transformed into a struct?

Thanks!

**Comment by jamonholmgren** [comment]
ProMotion-form has been officially deprecated. Thanks everyone!

http://jamonholmgren.com/deprecating-promotion-form/
