### ISSUE TITLE
Recreate examples from FXForms in RM

### ISSUE THREAD

**Issue by GantMan** [infinitered/ProMotion-form#25]
As you can see, there's a lot of good examples in FX Forms.
https://github.com/nicklockwood/FXForms/tree/master/Examples

Some are not applicable here (e.g. Storyboard and Swift), but it would be nice to get the application examples as illustrative.  Especially a "Kitchen Sink" version.

**Comment by jamonholmgren** [comment]
ProMotion-form has been officially deprecated. Thanks everyone!

http://jamonholmgren.com/deprecating-promotion-form/
