### ISSUE TITLE
Easier way to observe text changes?

### ISSUE THREAD

**Issue by markrickert** [infinitered/ProMotion-form#30]
I'm wanting to observe text field changes in a form and wondering if there's any better way to do this or if maybe we could make it a bit easier/readable?

Using bubblewrap's KVO methods:

```ruby
  def on_appear
    # Observes the text field value in the 2nd section, first cell.
    observe(self.formController.fieldForIndexPath(NSIndexPath.indexPathForRow(0, inSection:1)), :value) do |old_value, new_value|
      mp new_value
    end
  end

  def on_disappear
    unobserve_all
  end
```

Also, Merry Christmas! :christmas_tree: :santa: :snowman: :gift:

**Comment by jamonholmgren** [comment]
ProMotion-form has been officially deprecated. Thanks everyone!

http://jamonholmgren.com/deprecating-promotion-form/
