### ISSUE TITLE
Assertion failed: (node->objc_imp == imp), function add_method, file vm.cpp, line 1223.

### ISSUE THREAD

**Issue by pachun** [infinitered/ProMotion-form#34]
Here is a project reproducing the error:
`https://github.com/pachun/pm_form_screen_assertion_failure_demo`
clone, bundle, rake:pod install, and rake. Rake will get as far as simulation, then error with `Assertion failed: (node->objc_imp == imp), function add_method, file vm.cpp, line 1223.`

The cause is the combination of trying to open a PM::FormScreen and aliasing new on any class.

I think it's related to the FXForms cocoapod, but there are only two NSAsserts in it, and neither's description resemble this error. Still trying to figure it out from my end, but I thought I'd see if you guys knew anything offhand.

**Comment by pachun** [comment]
update, I found a way around this in my code. However, this is still an issue with PM::FormScreen. Not sure how important it is to you.

My goal was to have all class methods forwarded to a singleton. I also wanted to be able to send :new to the class and have it get forwarded to the singleton. I got that working like this:

```ruby
module MotionRest
  class Controller
    @@instance = nil

    def self.instance
      unless @@instance
        Dispatch.once { @@instance = new }
      end
      @@instance
    end

    def self.new
      if @@instance.nil?
        puts "in new"
        super
      else
        puts "forwarding to instance"
        @@instance.new
      end
    end

    def new
      puts "IN THE INSTANCE's NEW METHOD"
    end
  end
end
```

**Comment by jamonholmgren** [comment]
Wow, interesting structure there! 

I've wondered if anyone would implement `new` as an instance method. I use `obj = obj.new if obj.respond_to?(:new)` all over to allow you to pass in classes, which would blow up if you actually implemented `new` in your instance. :smile: 

Example:

```
open MyScreen
```

**Comment by jamonholmgren** [comment]
ProMotion-form has been officially deprecated. Thanks everyone!

http://jamonholmgren.com/deprecating-promotion-form/
