### ISSUE TITLE
Add a safety check when action methods don't accept an argument

### ISSUE THREAD

**Issue by andrewhavens** [infinitered/ProMotion-form#44]
I'm reporting this as an idea to save people (myself) from making this mistake in the future. When you define a cell with an `:action`, it's important to define the action method to accept the cell as an argument. Otherwise the app will crash without any explanation.

So I was thinking, maybe we could add a safety check to make sure the method is defined and accepts the correct number of arguments before passing the data to FXForms.

**Comment by jamonholmgren** [comment]
Should be easy enough with `#method.arity`. Watch for negative arity, though, if it's an optional arg.

**Comment by jamonholmgren** [comment]
ProMotion-form has been officially deprecated. Thanks everyone!

http://jamonholmgren.com/deprecating-promotion-form/
