### ISSUE TITLE
Text inputs get submitted as float

### ISSUE THREAD

**Issue by michaeljkchoi** [infinitered/ProMotion-form#47]
I only noticed this after the iOS 9 and RM 4.0 update.  I don't know if this is just coincidence or if something got changed in that update that's breaking.

The issue is that on text fields, when you input certain strings, the submitted value is some kind of float instead of the string I had inputted.  For example, I have a login screen.
    
    class LoginFormScreen < PM::FormScreen
      def form_data
        [{
          cells: [
            {
              name: "user_email",
              type: :email
            },
            {
              name: "password",
              type: :password
            }
          ]
        }]
      end

      def create_session
        dismiss_keyboard
        puts render_form
      end
    end

When I submit the form with the values (username // password), it yields:
thisisatest // thisisatest
    {:user_email=>-6.3752909523781e-149, :password=>-6.3752909523781e-149}

test2222 // test3333
    {:user_email=>"test2222", :password=>"test3333"}

Any idea what's up?  I'm using ProMotion-form 0.3.2.

**Comment by michaeljkchoi** [comment]
I get this error only when running on a device (or simulator) with iOS 9.  It works as expected for iOS 8.4.

I tried this in a clean Rubymotion project with only ProMotion and ProMotion-form, and this error still persists.

**Comment by andrewhavens** [comment]
^ this :sob:

**Comment by andrewhavens** [comment]
This is currently the hack that we are using to manually fetch the data. This form only has name and description text fields. Note that calling `.last` is actually the first field and `.first` is the last field.

```ruby
  def render_form_data
    data = render_form
    # HACK: in iOS9 odd numbered strings crash the app
    if data[:name].is_a?(Float) || data[:name].is_a?(Fixnum)
      data[:name] = find(UITextField).last.data
    end
    if data[:description].is_a?(Float) || data[:description].is_a?(Fixnum)
      data[:description] = find(UITextField).first.data
    end
    data
  end
```

**Comment by michaeljkchoi** [comment]
I actually switched to [ProMotion-XLForm](https://github.com/bmichotte/ProMotion-XLForm).  It does a pretty good job and the underlying [XLForm](https://github.com/xmartlabs/XLForm) seems to get a lot more support than [FXForms](https://github.com/nicklockwood/FXForms).

**Comment by michaeljkchoi** [comment]
Also #48

**Comment by jamonholmgren** [comment]
:+1:

**Comment by lbrezilien** [comment]
I installed the Promotion-XLForm gem and copied the example form into a screen and it no longer compiles, I keep getting an initialized constant (Name error)

**Comment by lbrezilien** [comment]
The specific error is : 
xl_form_patch.rb:123:in `section_options:': uninitialized constant XLFormSectionDescriptor::XLFormSectionOptionNone (NameError)

**Comment by andrewhavens** [comment]
@lbrezilien Did you remember to run `rake pod:install`? If that's not the issue, I would recommend posting this issue on the [Promotion-XLForm repo](https://github.com/bmichotte/ProMotion-XLForm).

**Comment by lbrezilien** [comment]
yes I've done that several times, even did a 'rake clean && rake' but I keep getting the error, I will post it  in the repo, any other suggestions in the mean time?
