### ISSUE TITLE
Considering Deprecating ProMotion-form

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ProMotion-form#48]
I'm considering deprecating PM-form. @bmichotte has an excellent alternative called [ProMotion-XLForm](https://github.com/bmichotte/ProMotion-XLForm), and we've been having a lot of issues with the underlying FXForms CocoaPod, which is a bit finicky. And I would probably use PM-XLForm if I were to start a form screen today.

Of the 22 people watching this repo, I'd like to get some feedback on this. Yes, no, indifferent?

**Comment by bmichotte** [comment]
I'm waiting for you, your PR and your requests guys ;)

**Comment by andrewhavens** [comment]
@jamonholmgren I support the idea of fully supporting a single form framework. ProMotion-XLForm has a lot of similarities and a lot of great features, so it seems like it has the potential to fully replace ProMotion-form. However, I think it's still too early to say ProMotion-XLForm is a "production-ready" replacement. There are some things in ProMotion-form that are currently a lot easier to do than in ProMotion-XLForm (specifically custom table cells, specifying cell images, etc). In addition, I'm working on resolving a critical bug that is crashing my app. Overall, I like the idea of shifting support to bringing ProMotion-XLForm up to speed and becoming the "official" form framework.

**Comment by bmichotte** [comment]
@andrewhavens Like I said to @jamonholmgren, I'll be happy to receive PR or feature requests. So feel free to spam PM-XLForm issues :)

**Comment by andrewhavens** [comment]
@bmichotte I saw it. ;) I'll try my best.

**Comment by jamonholmgren** [comment]
Thanks @andrewhavens, good feedback to have. I know @bmichotte is great about supporting PM-XLForms (something I sadly have not been with regard to this gem), so hopefully it will hit parity+ with PM-form soon.

**Comment by markrickert** [comment]
Honestly, i've been converting all my projects to XLForm. I've even made some pull requests to the project (as usual :smile:). It just seems easier to use without the mess of objective-c code that is `FXFormViewController`

**Comment by jamonholmgren** [comment]
ProMotion-form has been officially deprecated. Thanks everyone!

http://jamonholmgren.com/deprecating-promotion-form/
